version: '3.8'

services:
  postgres:
    image: postgres:latest
    container_name: pokecard-db
    environment:
      POSTGRES_DB: pokecard
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 1234
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    restart: unless-stopped

volumes:
  postgres_data: